- src/grid/Container/index.jsx
- src/grid/Container/style.css.js
- src/grid/Readme.md
This will enable to have fluid containers when needed on certain breakpoints, so we can easily removed the extra gutter on certain screens :)
> responsive containers

- index.d.ts
- package-lock.json
- package.json
> Add typescript typings

- index.d.ts
> Add nogutter prop to Row and bump version

- package.json
- src/grid/Row/index.jsx
> Closes #45 and bump to 3.0.7

- src/grid/Col/index.jsx
- src/grid/Col/style.js
- src/utils.js
Hi,
This PR is a proposal to add custom columns quantity support to grid using context, the same way as other properties of the grid/col are customized.
Your feedback will be very appreciated.
Kind regards
> support to change grid column qty

- src/grid/Col/index.jsx
- src/grid/Container/index.jsx
- src/grid/Row/index.jsx
for example sometimes you want more semantic so you will use a `section` instead `div`
> added optional custom component

- index.d.ts
> fix(types): add `component` prop to Col, Container, and Row components

- src/grid/Col/index.jsx
- src/grid/Col/style.js
This PR is adressing #101 
It allows setting a Col to be sized to its content.
```
<Row>
<Col>Flexible col</Col>
<Col xs="content">Col sized to content</Col>
</Row>
```
> Col width adapted to content

- package-lock.json
- package.json
> Make the build cross-platform

- index.d.ts
Fixes issue: https://github.com/JSxMachina/react-grid-system/issues/109
> Add optional gutterWidth to typescript interface

- index.d.ts
It allows to use useScreenClass() with TypeScript
> Add useScreenClass() into index.d.ts

- index.d.ts
> Add an parameter 'elementRef' to useScreenClass()

- src/grid/Col/style.js
- src/grid/Container/style.js
- src/grid/Row/style.js
I needed to replace some default grid styles, but it was impossible.
The problem was that the "moreStyles" were merged before the component styles.
With this PR i moved the moreStyles to the end of the styles function and it allowed me to change anything that i want.
Thanks!
> Allow style override

- index.d.ts
- src/grid/Col/index.jsx
- src/grid/Col/style.js
This property allow the column to have an specific fixed width or an automatic one.
No breaking changes =)
```jsx
<Row>
<Col width="150">
<ProductImage />
</Col>
<Col>
<ProductTitle />
<ProductPrice />
<ProductCoupon />
</Col>
</Row>
```
> Add width property to Col component

- index.d.ts
> allow "content" value on Col responsive props when using typescript

- index.d.ts
I didn't check to see if there were other missing types. Just ran across this one while implementing it in some TSX files.
> Add `nowrap` prop to TS definition

- package.json
Adding peer dependency to allow usage with React 17.
> Support React 17.

- src/utils.js
Prevent unnecessary computations.
> Improve performance of useScreenClass

- index.d.ts
This relates to https://github.com/sealninja/react-grid-system/issues/180
> Update return value of useScreenClass to be ScreenClass

- index.d.ts
- src/grid/Row/index.js
- src/grid/Row/style.js
Removed `nowrap` prop
Added `wrap` prop to set value of flex-wrap
Breaking Change:
`nowrap` has to be replaced with `wrap="nowrap"`
@gerbenmeyer please review.
> add support for wrap reverse

- src/config.js
- src/context/ScreenClassProvider/index.js
- src/grid.md
- src/grid/Col/index.js
- src/grid/Col/style.js
- src/grid/Container/index.js
- src/grid/Container/style.js
- src/utilities/Hidden/index.js
- src/utilities/Hidden/style.js
- src/utilities/Visible/index.js
- src/utilities/Visible/style.js
- src/utils.js
in my project, I needed an even larger breakpoint to check permissions greater than 1920, as well as ordering columns at different breakpoints.
I think it will be useful for other developers as well.
> added order param to Col && added xxxl breakpoint. Added doc to row.md

- index.d.ts
- package.json
add type order to Col
up version
add type xxxl to ScreenClass
> Pull request 259 fix typo 
