sealninja/react-grid-system

src/grid/Col/index.jsx, src/grid/Container/index.jsx, src/utilities/Hidden/index.jsx, src/utilities/ScreenClassRender/index.jsx, src/utilities/Visible/index.jsx
These changes significantly reduce my webpack bundle generated when using this package. Without the path to the function all of lodash was included in my build. From 565kb down to 54kb. You could also use this https://www.npmjs.com/package/babel-plugin-lodash but since just throttle was used I thought it would be quicker with search and replace.
=> replace lodash bracker import with a full path

index.d.ts, package.json
So it turns out I forgot to add index.d.ts to the files array in package.json. This fixes it, fixes the typescript definitions and bumps the version to 3.0.3.
=> Fix typescript definitions and bump version to 3.0.3

README.md, package.json
So I am bundling this component in with my app and adding it was adding over 30kb to a single lazily loaded route and I couldn't figure out why. It turns out that it was because I am was using a different React & React DOM version. Since React was listed as a dependency of this module and not a peerDependency then npm actually was installing two versions of React instead of one. 
For libraries like react-grid-system you really want to use peerDependencies to eliminate the possibility of two version of react so this PR changes that and adds instruction to the Readme on how to install using peerDependencies.
The good news: This library works with React 16 (though the version of styleguideist that we're using doesn't seem to)!
=> Use peer dependencies

index.d.ts
Type errors for boolean when using in our React/typescript/nextjs project, as the offset value is a number, changing the type to number fixes the type error so that project is now compiling normally and pass tests.
=> Edit offset types so number instead of booleans

index.d.ts
Fixes the error in #60 .
Change from `enum` to `union` type for Align prop. Now it works with TypeScript in the way the documentation explains it.
=> Fix #60 - Use Union type instead of enum with Align

index.d.ts
Since there are things like these (code below), typescript should know that you can pass basic div attributes
```
const {
children, xs, sm, md, lg, xl, offset, pull, push, debug, style,
...otherProps
} = this.props;
.....
<div style={theStyle} {...otherProps}>
{children}
</div>
```
this helps extending components for example with styled components
=> Add div attributes type definitions to Row, Col, Container

index.d.ts
Hi, I found that typing for the `setConfiguration` is missing. This PR adds type definition for it.
=> Add typescript definitions for setConfiguration

index.d.ts
Hey!
I've changed type definitions for `push` and `pull` props to `number` to match docs :)
=> Fix type definitions for push and pull props

src/grid/Col/index.jsx, src/grid/Container/index.jsx, src/grid/Row/index.jsx
**Fix component prop type validation**
react-grid-system version: 4.2.0
chrome version: 68.0.3440.106
**Description**
After passing `component` property to any of `Contrainer`, `Col`, `Row`, following warnings are visible in the console.
```Failed prop type: Invalid prop `component` supplied to `Contrainer`.```
```Failed prop type: Invalid prop `component` supplied to `Col`.```
```Failed prop type: Invalid prop `component` supplied to `Row`.```
**Used code**
- I am trying to render styles using glamorous library, so I do not have long style attributes in the DOM.
```jsx
import * as reactGridSystem from "react-grid-system";
import glamorous from "glamorous";
import React, { Component } from "react";
class ProxyComponent extends Component {
render () {
const { style, ...rest } = this.props; …
```
=> Fix component prop type validation

package-lock.json, src/context/ScreenClassProvider/index.jsx, src/utils.js
Added a prop called `useOwnWidth` to the `ScreenClassProvider` component.
When provided, it adds a container and uses that as source for the screenclass dimensions.
=> Ability to use own dimensions instead of window

index.d.ts
Fixed typings for `ScreenClassProvider` children prop.
Fixes #92
=> Fix typings for ScreenClassProvider props

src/grid/Readme.md, src/grid/Row/index.jsx
Add flex box option 'stretch' to the align prop so you can set columns inside a row to be equal heights.
Also add the new option into the readme.
=> Update 'align' prop validation

src/grid/Row/index.jsx, src/grid/Row/style.js
This PR addresses #102
It adds a `nowrap` prop to `Row` that simply sets the `flex-wrap` css property to `nowrap`. 
Especially useful when using the `content` Col sizing as described in #104 .
```
<Row>
<Col xs="content">very long content...</Col>
<Col></Col>
</Row>
```
=> Add nowrap option to Row

index.d.ts
`ScreenClassProviderProps` type did not include `fallbackScreenClass` and `useOwnWidth` props.
The `index.d.ts` file was also repetitive so I dried it a little bit:
- Instead of specifying screen classes literally there now is a `ScreenClass` type
- Instead of specifying map types that have screen class as a key there now is a `ScreenClassMap` type
=> Fix typings for ScreenClassProviderProps. Fixes #134

index.d.ts
Previous typing didn't allow passing string component
=> Fix broken typescript component prop type definition

package.json, src/grid/Col/style.js
Hi,
I'm using your module, and I have a warning during the snapshots generation in Storybook v5.3.19:
**Warning: Updating a style property during rerender (flexBasis) when a conflicting property is set (flex) can lead to styling bugs. To avoid this, don't mix shorthand and non-shorthand properties for the same value; instead, replace the shorthand with separate values.**
This PR will fix it.
I just replaced the shorthand reset with the non-shorthand props.
=> replaced shorthand with non-shorthand props to avoid warnings

src/context/ScreenClassProvider/index.js, src/grid/Col/index.js, src/grid/Col/style.js, src/grid/Container/index.js, src/grid/Container/style.js, src/grid/Row/index.js, src/grid/Row/style.js, src/primitives/Div/index.js, src/primitives/Div/index.native.js, src/primitives/Span/index.js, src/primitives/Span/index.native.js, src/primitives/Window/index.js, src/primitives/Window/index.native.js, src/primitives/index.js, src/utils.js
I think the library is really nice. I want to use with react-native for mobile apps. To work with react-native, I added react-native primitives with files which are ending with .native.js . When react-native bundler is running, it will understand which file it should be used. Here is the things which I've changed in short: 
- Add View and Dimensions API to use instead of 'div', 'span', window
- Change defaultProps.component with new primitives
- Change style measurement strings with numbers (react-native does not support string px measurements ("10px"), it converts number values automatically. Also react automatically appends "px" for number values on web application. So it will work on both platform.)
- Change window with Window ( I added just few functions which the library uses )
I …
=> Support React Native

src/grid/Container/style.js
```js
if (fluid && (!sm && !md && !lg && !xl)) {    
return { ...styles, ...moreStyle };  
}
```
When we use `<Container fluid xs>`, the above code block evaluates to `true` and returns styles that don't contain max-width regardless of the screen size.
This change adds `!xs` to the `if` condition so that this condition evaluates to `false` when `fluid xs` prop is used on `Container`. Also separated the `xs` and `sm` max width so `sm` max-width continues to work when using `xs`.
Fixes #177
=> Fix: fluid xs makes Container max width on all screen sizes

index.d.ts
This PR includes a few type fixes for React v18 types. Those newer types don't include children by default, so they must be named explicitly or one gets type errors like the following:
```
index.tsx:583:24 - error TS2769: No overload matches this call.
Overload 1 of 2, '(props: Partial<Record<ScreenClass, boolean>> | Readonly<Partial<Record<ScreenClass, boolean>>>): Hidden', gave the following error.
Type '{ children: Element; xs: true; sm: true; md: true; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Hidden> & Readonly<Partial<Record<ScreenClass, boolean>>>'.
Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Hidden> & Readonly<Partial<Record<ScreenClass, boolean>>>'.
Overload 2 of 2, '(props: …
```
=> Improve Types for React v18 Compatibility

src/grid/Col/index.js, src/grid/Container/index.js, src/grid/Row/index.js
Display names help with debugging and (as the name implies) "displaying" component names.
It helps in situations where the display name cannot be derived, such as with a forward ref.
This change will allow these components to always be displayed properly in tools like Storybook and React Dev Tools.
=> Fix: Add Display Names

src/context/ScreenClassProvider/index.js, src/grid/Col/index.js, src/grid/Container/index.js, src/grid/Row/index.js, src/utilities/Hidden/index.js, src/utilities/Visible/index.js
This PR addresses the upcoming deprecation of `defaultProps` in function components as signaled by React's warning: "Warning: ScreenClassProvider: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead." The changes involve updating the `ScreenClassProvider`, `Col`, `Container`, `Row`, `Hidden`, and `Visible` components within the `react-grid-system` library to use default function parameters for props instead of relying on `defaultProps`. This update ensures forward compatibility with future versions of React and adheres to modern JavaScript best practices.
- **ScreenClassProvider**: Default parameters are set directly in the function signature for `useOwnWidth`, `children`, and `fallbackScreenClass`.
- …
=> Refactor: Replace defaultProps with Default Function Parameters
